// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "로그인 및 토큰 발급 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "로그인",
                "parameters": [
                    {
                        "description": "로그인 요청 파라미터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "ErrShouldBindJson(5001): 잘못된 JSON 형식입니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "ErrPasswordMismatch(100): 비밀번호가 일치하지 않습니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "ErrUserNotFound(101): 존재하지 않는 아이디입니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "ErrInternalServer(5000): 토큰 발급 실패",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh Token을 사용하여 새로운 Access Token 발급",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "토큰 갱신",
                "parameters": [
                    {
                        "description": "토큰 갱신 파라미터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.AuthRefreshResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "ErrShouldBindJson(5001): 잘못된 JSON 형식입니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "ErrUnauthorized(106): 유효하지 않거나 만료된 refresh token입니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "ErrInternalServer(5000): 토큰 발급 실패",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "회원가입을 위한 API. ID, 비밀번호, 닉네임 정보를 받아 회원을 등록합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "회원가입",
                "parameters": [
                    {
                        "description": "회원가입 요청 파라미터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    },
                    "400": {
                        "description": "ErrShouldBindJson(5001): 잘못된 JSON 형식입니다. / ErrUserAlreadyExists(103): 이미 존재하는 사용자입니다.",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "ErrInternalServer(5000): 비밀번호 암호화 실패 / ErrDatabase(9999): 사용자 저장 실패",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.RoleType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                999
            ],
            "x-enum-varnames": [
                "DefaultRole",
                "UserRole",
                "OrganizationRole",
                "AdminRole"
            ]
        },
        "errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "에러 코드",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.ErrorCode"
                        }
                    ]
                },
                "message": {
                    "description": "사용자에게 노출할 메시지",
                    "type": "string"
                }
            }
        },
        "errors.ErrorCode": {
            "type": "integer",
            "enum": [
                100,
                101,
                102,
                103,
                104,
                105,
                106,
                107,
                108,
                109,
                1001,
                1002,
                2001,
                3001,
                5000,
                5001,
                5003,
                5004,
                9999
            ],
            "x-enum-varnames": [
                "PasswordMismatchErrorCode",
                "UserNotFoundErrorCode",
                "EmailAlreadyExistsErrorCode",
                "UserAlreadyExistsErrorCode",
                "InvalidAuthHeaderErrorCode",
                "TokenMissingErrorCode",
                "UnAuthorizedErrorCode",
                "RoleUpgradeRequestNotFoundErrorCode",
                "ForbiddenErrorCode",
                "BadRoleUpgradeRequestErrorCode",
                "EmailVerificationErrorCode",
                "EmailVerificationNotFoundErrorCode",
                "PostNotFountErrorCode",
                "FileNotFoundErrorCode",
                "InternalServerErrorCode",
                "ShouldBindJsonErrorCode",
                "ParseTemplateErrorCode",
                "ApplyTemplateErrorCode",
                "DBErrorCode"
            ]
        },
        "v1.AuthRefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "v1.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "v1.RegisterRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.RoleType"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer {access_token}\" 형식으로 전달합니다. 로그인(` + "`" + `/auth/login` + "`" + `) 또는 회원가입(` + "`" + `/auth/register` + "`" + `) 응답으로 발급된 access_token을 사용하세요.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Limit Hackathon",
	Description:      "back-end API for limitthon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
